### PR TITLE
VeNFT: tokenId–pool voting model (`VeNFTState`, `VeNFTPoolVote`)

### LINKED ISSUE #506: Incorrect `(user, pool)` vote accounting due to veNFT ownership & managed-NFT semantics
### Summary
We currently track voting power directly at the `(user, pool)` level by adding `Voted` weights and subtracting `Abstained` weights. This is incorrect for the Velodrome V2 `Voter` contract because voting power is owned by **veNFT tokenIds**, not user addresses.

### Problem
The on-chain state is keyed by `(tokenId, pool)`, but events expose a `voter` (msg.sender). This causes multiple attribution issues:

- **veNFT ownership changes**
  - veNFTs are ERC721s and can be transferred.
  - Ownership changes reassign voting power, but **no `Voted` or `Abstained` events are emitted**.
  - `(user, pool)` balances silently drift unless transfers are handled.

- **Managed veNFT flows**
  - `depositManaged`, `withdrawManaged`, and `poke` can recast votes on a *managed tokenId*.
  - The event `voter` is not guaranteed to be the owner or beneficiary of the votes.
  - Votes must be attributed to the owner of the **tokenId that holds them**, not the caller.

- **Incorrect power reassignment**
  - Moving total ve power on veNFT transfer is wrong.
  - Only per-pool `votes[tokenId][pool]` (or `usedWeights[tokenId]`) represent active voting weight.

### Correct Model / Proposed Fix
- Treat **veNFT (`tokenId`) as the primary voting account**.
- Track vote state at the **`(tokenId, pool)`** level using `Voted` / `Abstained` deltas.
- Track veNFT ownership via **VotingEscrow ERC721 `Transfer` events**.
- Derive `(user, pool)` as: Σ votes[tokenId][pool] for all tokenIds currently owned by user
- (Optional) Materialize `(user, pool)` by reassigning `(tokenId, pool)` balances on veNFT transfer events.**

### PR DESCRIPTION
**Pull request by FonsSicca**
closes #506 (following PR also addresses/completes this)

The following document has some queries (and their purpose) in terms of check correctness of fields/entities related to this PR (and following PR for `Voter.ts`):

https://www.notion.so/VeNFT-and-Voter-related-entity-fields-Correctness-check-2e90016b292780049a51fe5114cb14c4?source=copy_link

Implements:
- Paradigm change in the way votes are accounted: voting is actually associated to each `tokenId`, therefore we changed the previously logic existing for `veNFT` event handlers and `Voter` (in the next PR) that used `pool vote <-> user` relationship to `pool vote <-> tokenId relationship`.

## Summary by CodeRabbit

* **New Features**
  * Pool-specific veNFT voting and per-pool staking metrics
  * Multi-token operations (merge/split) and enhanced deposit/withdraw flows
  * New management controls for managers, voters, and distributors

* **Refactor**
  * Redesigned veNFT state model and streamlined event processing for more accurate state updates

* **Bug Fixes**
  * Expanded error and event surface for clearer operational feedback

### CODE REVIEW

File: test/EventHandlers/Pool/common.ts [hunk 1]
```diff
@@ -231,6 +233,25 @@ export function setupCommon() {
     lastAlmActivityTimestamp: new Date(900000 * 1000),
   };
 
+  const mockVeNFTStateData: VeNFTState = {
+    id: `${CHAIN_ID}_1`,
+    chainId: CHAIN_ID,
+    tokenId: 1n,
+    owner: normalizedDefaultUserAddress,
+    locktime: 0n,
+    lastUpdatedTimestamp: new Date(900000 * 1000),
```
Comment (WooSungD) [inline test/EventHandlers/Pool/common.ts]: [minor; non-blocking] What is the significance of `Date(900000 * 1000)` value? Is it just a default value?

**Review by WooSungD — APPROVED** [review]
Nice!
